import { Letter } from './types';

// Data extracted from the provided images
export const LETTERS_DATA: Letter[] = [
  {
    id: '1',
    letterCode: '1772282',
    name: 'Paulo Alexandre',
    age: 4,
    gender: 'M',
    schoolYear: 'Educação Infantil',
    requestSummary: 'Fantasia Homem Aranha c/ Máscara',
    fullTranscription: 'Moro no abrigo com meus dois irmãos maiores... gostaria de uma fantasia completa do homem aranha e máscara. Um beijo do seu amiguinho Paulo Alexandre.',
    categories: ['Brinquedo', 'Roupa'],
    status: 'available'
  },
  {
    id: '2',
    letterCode: '1772296',
    name: 'Mikaelly Rosa',
    age: 5,
    gender: 'F',
    schoolYear: 'Jardim B',
    requestSummary: 'Bicicleta',
    fullTranscription: 'Moro no abrigo com mais duas irmãs menores, ano que vem vou para o Jardim B, gosto de brincar de boneca e andar no pátio. Gostaria de uma bicicleta para poder pedalar e aproveitar os dias de verão.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '3',
    letterCode: '1772304',
    name: 'Aurora Rosa da Fonseca',
    age: 1, // 1 ano e 9 meses
    gender: 'F',
    schoolYear: 'Berçário',
    requestSummary: 'Triciclo (de empurrar)',
    fullTranscription: 'Me chamo Aurora tenho 1 e 9 meses, moro no abrigo com mais 2 manas. Sou carinhosa e carismática... gostaria de ganhar um triciclo para que possa passear com as tias do abrigo pois já sou grandinha mas tenho dificuldades para caminhar.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '4',
    letterCode: '1776617',
    name: 'Alexandro Suis',
    age: 13,
    gender: 'M',
    schoolYear: '7º Ano',
    requestSummary: 'Roupas, Tênis, Bicicleta',
    fullTranscription: 'Roupas (Tam M), Tênis (38-39), Bicicleta, Mochila, Material Escolar.',
    categories: ['Roupa', 'Calçado', 'Brinquedo', 'Material Escolar'],
    status: 'available'
  },
  {
    id: '5',
    letterCode: '1769349',
    name: 'Arthur Medeiros de Matos',
    age: 15,
    gender: 'M',
    schoolYear: '7º Ano',
    requestSummary: 'Conjunto Mizuno G e Tênis 41',
    fullTranscription: 'Querido papai noel gostaria de ganhar um conjunto da mizuno tudo G e um Tênis Mizuno 14 numero 41.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '6',
    letterCode: '1769375',
    name: 'Gabriel Jesus Carvalho',
    age: 17,
    gender: 'M',
    schoolYear: '9º Ano',
    requestSummary: 'Conjunto Nike G e Tênis 41',
    fullTranscription: 'Querido papai noel eu quero de presente um conjunto da Nike e um tenis da Mizuno (numero do tenis 40, 41).',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '7',
    letterCode: '1769431',
    name: 'João Vitor da Silva Borges',
    age: 16,
    gender: 'M',
    schoolYear: '8º Ano',
    requestSummary: 'Conjunto Adidas G e Tênis Nike 40',
    fullTranscription: 'Querido Papai Noel gostaria de ganhar um conjunto da Adidas e um tênis da Nike nº 40.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '8',
    letterCode: '1769473',
    name: 'Jonathan da Silva Viegas',
    age: 15,
    gender: 'M',
    schoolYear: '7º Ano',
    requestSummary: 'Tênis 39, Jaqueta e Bermuda',
    fullTranscription: 'Querido Papai Noel, gostaria de ganhar um Tênis da Mizuno (preto) 38-39, Jaqueta da Quik Silver e Bermuda da Nike.',
    categories: ['Calçado', 'Roupa'],
    status: 'available'
  },
  {
    id: '9',
    letterCode: '1769511',
    name: 'Nicolas dos Santos Aires',
    age: 17,
    gender: 'M',
    schoolYear: '9º Ano',
    requestSummary: 'Relógio, Material Escolar, Tênis 40',
    fullTranscription: 'O Nicolas gostaria de ganhar presentes coloridos e divertidos, ele não consegue escrever por isso estamos ajudando. Relógio, Material escolar colorido e divertido, Tênis 40, Roupas XG.',
    categories: ['Outros', 'Material Escolar', 'Calçado', 'Roupa'],
    status: 'available'
  },
  {
    id: '10',
    letterCode: '1769544',
    name: 'Wesley Kauê Telohen',
    age: 17,
    gender: 'M',
    schoolYear: '7º Ano',
    requestSummary: 'Tênis 42 e Boné Quick',
    fullTranscription: 'Querido papai noel eu quero um boné da quiquisilver pura papa e um Tenis da mizuno para papar 41 ou 42.',
    categories: ['Calçado', 'Roupa'],
    status: 'available'
  },
  {
    id: '11',
    letterCode: '1769575',
    name: 'Lucas Rogério de Matos',
    age: 15,
    gender: 'M',
    schoolYear: '7º Ano',
    requestSummary: 'Tênis 38, Chinelo 38, Relógio',
    fullTranscription: 'Papai Noel quero ver se consegue me dar de presente 1 relógio bonito, 1 tenis 38, 1 Boné e 1 chinelo 38.',
    categories: ['Calçado', 'Outros', 'Roupa'],
    status: 'available'
  },
  {
    id: '12',
    letterCode: '1769598',
    name: 'Enzo da Silva Lopes',
    age: 14,
    gender: 'M',
    schoolYear: '6º Ano',
    requestSummary: 'Conjunto Barcelona G e Tênis 41/42',
    fullTranscription: 'Querido papai noel, gostaria de ganhar um Conjunto do Barcelona (Bermuda e Camiseta Tam M) e um tênis mizuno Tam 41/42.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '13',
    letterCode: '1769728',
    name: 'Gabriel Barcelos',
    age: 14,
    gender: 'M',
    schoolYear: '6º Ano',
    requestSummary: 'Camiseta G, Calça e Tênis 42',
    fullTranscription: 'Querido papai noel eu gostaria de ganhar uma camisa quiksilver, tamanho G, uma Calça da nike, e um tênis da mizuno tamanho 42.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '14',
    letterCode: '1769827',
    name: 'Jonatan Francisco Rodrigues',
    age: 15,
    gender: 'M',
    schoolYear: '7º Ano',
    requestSummary: 'Boné, Brinco, Calça de Time G',
    fullTranscription: 'Querido Papai Noel eu queria de Presente: Um bone, Um brinco, Uma calça de time G.',
    categories: ['Roupa', 'Outros'],
    status: 'available'
  },
  {
    id: '15',
    letterCode: '1769866',
    name: 'Nicolas Manoel Menezes',
    age: 15,
    gender: 'M',
    schoolYear: 'Ensino Médio',
    requestSummary: 'Conjunto Flamengo G e Tênis 42',
    fullTranscription: 'Papai Noel gostaria de ganhar: Conjunto do Flamengo G, Tenis Nike 41/42.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '16',
    letterCode: '1769891',
    name: 'Kauã da Silva Torres',
    age: 15,
    gender: 'M',
    schoolYear: '7º Ano',
    requestSummary: 'Tênis Mizuno 40, Camisa G Hurley',
    fullTranscription: 'Querido Papai noel, Gostaria de ganhar um tênis mizuno 43 (pé 39/40), e uma Camisa G, da hurley.',
    categories: ['Calçado', 'Roupa'],
    status: 'available'
  },
  {
    id: '17',
    letterCode: '1857797',
    name: 'Andressa (Bernardo)',
    age: 15,
    gender: 'F',
    schoolYear: '8º Ano',
    requestSummary: 'Maquiagem, Livros, Salto 40',
    fullTranscription: 'Eu desejava de presente, maquiagem, um box de livros da cronica de gelo e fogo, salto alto numero 40, um patins numero 40. E um livro de bruxaria varken luckland.',
    categories: ['Outros', 'Brinquedo', 'Calçado'],
    status: 'available'
  },
  {
    id: '18',
    letterCode: '1780164',
    name: 'Bruno Gustavo Lopes',
    age: 15,
    gender: 'M',
    schoolYear: 'EJA',
    requestSummary: 'Relógio Digital, Conj. Flamengo, Vans 42',
    fullTranscription: 'Um relogio digital e um conj do flamengo e um vans e meu numero: 42.',
    categories: ['Outros', 'Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '19',
    letterCode: '1790369',
    name: 'Acacio Elisio',
    age: 12,
    gender: 'M',
    schoolYear: '4º Ano',
    requestSummary: 'Camisetas G3 e Calças Abrigo G3',
    fullTranscription: 'O Noel, aqui é o Acacio, me comportei durante o ano e queria receber esses presentes no final do ano: Camisetas G3, Calças de abrigo G3.',
    categories: ['Roupa'],
    status: 'available'
  },
  {
    id: '20',
    letterCode: '1780204',
    name: 'Karen Eduarda Santos',
    age: 17,
    gender: 'F',
    schoolYear: 'Ensino Médio',
    requestSummary: 'Chapinha, Tênis 37, Roupas 36',
    fullTranscription: 'Pedido da Criança: Chapinha Profissional, Tenis Puma, Roupas calça 36. Tênis 37.',
    categories: ['Outros', 'Calçado', 'Roupa'],
    status: 'available'
  },
  {
    id: '21',
    letterCode: '1780250',
    name: 'Lucas Soares',
    age: 14,
    gender: 'M',
    schoolYear: '7º Ano',
    requestSummary: 'Chuteira 38/39, Skate, Roupas',
    fullTranscription: 'Chuteira nº 38/39, Skate, Bermuda, Camiseta Skatista. Fantasia Garra.',
    categories: ['Calçado', 'Brinquedo', 'Roupa'],
    status: 'available'
  },
  {
    id: '22',
    letterCode: '1780336',
    name: 'Alice Medeiros',
    age: 16,
    gender: 'F',
    schoolYear: '8º Ano',
    requestSummary: 'Tênis 36, Jaqueta Jeans P',
    fullTranscription: 'Tênis, Jaqueta Jeans. Tenis nº 36.',
    categories: ['Calçado', 'Roupa'],
    status: 'available'
  },
  {
    id: '23',
    letterCode: '1780499',
    name: 'Alexsander Alves',
    age: 14,
    gender: 'M',
    schoolYear: '8º Ano',
    requestSummary: 'Bicicleta, Mini Game, Camisa Inter',
    fullTranscription: 'Bicicleta, Mini Game, Camisa do Inter com meu nome, Relógio, Perfume, Chuteira 43/44, Shampoo para caspa, Skate, Proteção para o skate.',
    categories: ['Brinquedo', 'Roupa', 'Calçado', 'Outros'],
    status: 'available'
  },
  {
    id: '24',
    letterCode: '1780516',
    name: 'Anthony Gabriel',
    age: 12,
    gender: 'M',
    schoolYear: '4º Ano',
    requestSummary: 'Minigame, Relógio, Corrente',
    fullTranscription: 'Minigame, Relogio, Corrente.',
    categories: ['Brinquedo', 'Outros'],
    status: 'available'
  },
  {
    id: '25',
    letterCode: '1780551',
    name: 'Ruan Martins',
    age: 15,
    gender: 'M',
    schoolYear: '6º Ano',
    requestSummary: 'Roupas M, Camiseta M, Calção 39',
    fullTranscription: 'Eu quero continuar morando na [ilegível] e quero Roupas, Camiseta (M), Calção (39).',
    categories: ['Roupa'],
    status: 'available'
  },
  {
    id: '26',
    letterCode: '1873839',
    name: 'Agatha Bencke Martins',
    age: 2,
    gender: 'F',
    schoolYear: 'Berçário II',
    requestSummary: 'Bonecas',
    fullTranscription: 'Pedido da Criança: Bonecas.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '27',
    letterCode: '1894854',
    name: 'Agatha Santos da Silva',
    age: 10,
    gender: 'F',
    schoolYear: '4º Ano',
    requestSummary: 'Roler Rosa 35 ou Maleta Maquiagem',
    fullTranscription: 'Querido papai noel eu gostaria de ganhar muito essas coisas de você: Roler Rosa Numero 35 ou uma Maleta de maquiagem.',
    categories: ['Brinquedo', 'Outros'],
    status: 'available'
  },
  {
    id: '28',
    letterCode: '1894865',
    name: 'Andrei Eoirian Barbosa',
    age: 10,
    gender: 'M',
    schoolYear: '4º Ano',
    requestSummary: 'Bicicleta Vikn Azul ou Roxo',
    fullTranscription: 'Eu gostaria de ganhar uma Vikn Azul ou Roxo. Esse ano voce podre ria me da uma bicicleta azul ou roxo uma vink muito obrigo.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '29',
    letterCode: '1894886',
    name: 'Cesar Pedro da Silva',
    age: 9,
    gender: 'M',
    schoolYear: '4º Ano',
    requestSummary: 'Carrinho de Controle Remoto',
    fullTranscription: 'Ness natal eu gostaria muito de ganha uma um carrinho de controle remoto com os cones de plasticozinho.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '30',
    letterCode: '1894873',
    name: 'Emilly Carolina Carvalho',
    age: 12,
    gender: 'F',
    schoolYear: '4º Ano',
    requestSummary: 'Bicicleta',
    fullTranscription: 'Querido papai noel eu queria muito uma bicicleta e um gloss da francine de mel.',
    categories: ['Brinquedo', 'Outros'],
    status: 'available'
  },
  {
    id: '31',
    letterCode: '1894907',
    name: 'Isabelli Santos Lima',
    age: 11,
    gender: 'F',
    schoolYear: '4º Ano',
    requestSummary: 'Conjunto Bermuda/Colar e Brinco',
    fullTranscription: 'Eu queria esses presentes porque nunca tive um. Porque minha mãe me deu um dela e eu queria um só pra mim. E um par de brinco de cereja e um conjunto de bermuda e camiseta.',
    categories: ['Roupa', 'Outros'],
    status: 'available'
  },
  {
    id: '32',
    letterCode: '1894915',
    name: 'Isabelly Ebertz',
    age: 10,
    gender: 'F',
    schoolYear: '4º Ano',
    requestSummary: 'Patinete',
    fullTranscription: 'Quero ganhar no natal um patinete.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '33',
    letterCode: '1894926',
    name: 'Jeferson Gabriel',
    age: 9,
    gender: 'M',
    schoolYear: '4º Ano',
    requestSummary: 'Saco de Boxe com Luvas',
    fullTranscription: 'Oi papai noel desculpa não escuta a profesoura mais vou esuquitar vou tentar pasar de ano que reum um saco de boxi com luvas de box.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '34',
    letterCode: '1894938',
    name: 'João Lucas Rrupo',
    age: 10,
    gender: 'M',
    schoolYear: '4º Ano',
    requestSummary: 'Sapato de Rodinhas 32',
    fullTranscription: 'Sapato de Rodinhas 32. Porque eu vi pessoas amado. Gostei de amado. Eu Sim. Por Favor.',
    categories: ['Calçado', 'Brinquedo'],
    status: 'available'
  },
  {
    id: '35',
    letterCode: '1894956',
    name: 'Kalebe Garsia',
    age: 12,
    gender: 'M',
    schoolYear: '4º Ano',
    requestSummary: 'Carrinho Nissan GTR ou Bola',
    fullTranscription: 'Gostaria de um carrinho de Nissan GTR R34 ou que não ter como compra prefiro que compre uma bola.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '36',
    letterCode: '1894968',
    name: 'Keuily Gabrielly',
    age: 10,
    gender: 'F',
    schoolYear: '4º Ano',
    requestSummary: 'Colar de Ouro e Creme',
    fullTranscription: 'A por que gosto e não tenho... preciso muito beijo. (Pedido: Uma colar de ouro, creme de rosto).',
    categories: ['Outros'],
    status: 'available'
  }
];
