import { Letter } from './types';

// Data extracted from the provided images
export const LETTERS_DATA: Letter[] = [
  {
    id: '1',
    letterCode: '1742132',
    name: 'Kelly Vitória',
    age: 15,
    gender: 'F',
    schoolYear: '8º Ano',
    requestSummary: 'Tênis e/ou Roupa',
    fullTranscription: 'Gostaria de ganhar um tênis da Sal e Pimenta Branco, Preto ou Branco e preto. Obs: Não precisa ser original. Ou eu queria 3 calças da Sal e Pimenta (tem um combo de 3) mas se não conseguir tudo bem... Calça Skinny num 38. Tênis num 36/37.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '2',
    letterCode: '1742145',
    name: 'Renata',
    age: 16,
    gender: 'F',
    schoolYear: '1º Ano',
    requestSummary: 'Calça Cargo e Tênis',
    fullTranscription: 'Gostaria de ganhar calças cargo jeans tam 54, e um Air Force branco Tam 37-38. Obrigado e feliz natal!!!',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '3',
    letterCode: '1742122',
    name: 'Isadora',
    age: 16,
    gender: 'F',
    schoolYear: '1º Ano',
    requestSummary: 'Tênis e/ou Roupa',
    fullTranscription: 'Air Force branco com preto (não precisa ser original), 3 calças da sal e pimenta tam 38, 5 croppeds de manga curta cor branca, preto, rosa, nude, vermelho tam M.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '4',
    letterCode: '1742173',
    name: 'Wesler',
    age: 16,
    gender: 'M',
    schoolYear: '8º Ano',
    requestSummary: 'Pijama Pikachu, Lacoste, Tênis',
    fullTranscription: 'Um pijama do pikachu masculino (não precisa ser original), conjunto da lacoste (não precisa ser original), tenis Air Force branco Tam 40/41. Obrigado feliz natal.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '5',
    letterCode: '1749083',
    name: 'Carlos Antônio Ferreira',
    age: 11,
    gender: 'M',
    schoolYear: '5º Ano',
    requestSummary: 'Uniforme Lamine Yamal / Tênis',
    fullTranscription: 'Sou do 5º ano e eu gosto muito de jogar bola e futevôlei... quero ganhar uma roupa do Lamine Yamal, e um conjunto da Nike, e um Court Vision, e um perfume. Calção é 12 e o número do tênis é 34/35.',
    categories: ['Roupa', 'Calçado', 'Outros'],
    status: 'available'
  },
  {
    id: '6',
    letterCode: '1750770',
    name: 'Felipe Sewero',
    age: 17,
    gender: 'M',
    schoolYear: '7º Ano',
    requestSummary: 'Bermuda e Camiseta TG',
    fullTranscription: 'Bermuda e Camiseta TG. Obrigado Papai Noel.',
    categories: ['Roupa'],
    status: 'available'
  },
  {
    id: '7',
    letterCode: '1750867',
    name: 'Kimberlly Gabriella',
    age: 13,
    gender: 'F',
    schoolYear: '7º Ano',
    requestSummary: 'Vestido e Papete',
    fullTranscription: 'Gostaria de pedir o vestido tomara que caia com abertura lateral e puxador super confortavel e também uma papete bege. Tamanho 12.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '8',
    letterCode: '1741697',
    name: 'Vida Mariana Gonçalves',
    age: 14,
    gender: 'F',
    schoolYear: '6º Ano',
    requestSummary: 'Short Jeans, Cropped e Sandália',
    fullTranscription: 'Quero um short jeans da Sal e Pimenta (Tamanho 36), e um cropped da Sal e Pimenta (Tamanho P), e uma sandália feminina salto alto de amarrar na perna Tamanho 35 ou 36 para eu passar o natal.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '9',
    letterCode: '1741239',
    name: 'Robert Lourenço Carpes',
    age: 7,
    gender: 'M',
    schoolYear: '2º Ano',
    requestSummary: 'Conjunto Lacoste e Tênis',
    fullTranscription: 'Quero muito ganhar um conjunto de roupa da marca Lacoste, tamanho 8 anos ou 10, ou gostaria também de um Tênis masculino Gucci solado bolha oversize preto. E também um boné branco.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '10',
    letterCode: '1741028',
    name: 'Ana Maria Cruz',
    age: 16,
    gender: 'F',
    schoolYear: '9º Ano',
    requestSummary: 'Calça Cargo e Bota',
    fullTranscription: 'Querido Papai Noel, eu ti peço uma Calça Cargo com corrente Tamanho 52 e uma Bota preta Coturno e um Cropped Tamanho 42.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '11',
    letterCode: '1741065',
    name: 'Bárbara Roberta',
    age: 16,
    gender: 'F',
    schoolYear: '9º Ano',
    requestSummary: 'Calça Cargo, Tênis e Chapinha',
    fullTranscription: 'Gostaria de ganhar uma calça cargo preta com correntes (38), um cropped preto de manga longa (P), tênis da Vans preto ou All Star botinha preto (36) e uma chapinha da marca Lizze.',
    categories: ['Roupa', 'Calçado', 'Outros'],
    status: 'available'
  },
  {
    id: '12',
    letterCode: '1741151',
    name: 'Emilly de Souza Escobar',
    age: 14,
    gender: 'F',
    schoolYear: '7º Ano',
    requestSummary: 'Escova Giratória, Perfume',
    fullTranscription: 'Escova giratória que seca, Perfume, Moletom tamanho XGG.',
    categories: ['Outros', 'Roupa'],
    status: 'available'
  },
  {
    id: '13',
    letterCode: '1741218',
    name: 'Lucas Gabriel Oliveira',
    age: 12,
    gender: 'M',
    schoolYear: '6º Ano',
    requestSummary: 'Roupa da Nike e Chuteira',
    fullTranscription: 'Eu gostaria de ganhar uma roupa da Nike e uma chuteira da Nike 39/40, um tenis da Oakley.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '14',
    letterCode: '1741261',
    name: 'Talita Maquardt',
    age: 17,
    gender: 'F',
    schoolYear: '-',
    requestSummary: 'Bota Preta e Chinelo',
    fullTranscription: 'Meu nome é Talita, gostaria de ganhar uma Bota Preta 38 e Chinelo Nuvem 38.',
    categories: ['Calçado'],
    status: 'available'
  },
  {
    id: '15',
    letterCode: '1720000',
    name: 'Thales',
    age: 11,
    gender: 'M',
    schoolYear: '5º Ano',
    requestSummary: 'Bicicleta',
    fullTranscription: 'Bicicleta. (Desenho de uma bicicleta verde).',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '16',
    letterCode: '1720108',
    name: 'Gabriel',
    age: 4,
    gender: 'M',
    schoolYear: 'Maternal 2',
    requestSummary: 'Piscina de Bolinha',
    fullTranscription: 'Sou Gabriel tenho 4 anos e quero ganhar de natal uma piscina de bolinhas.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '17',
    letterCode: '1729153',
    name: 'Kauã Victor Rosa',
    age: 11,
    gender: 'M',
    schoolYear: '4º Ano',
    requestSummary: 'Roupa e Tênis (38)',
    fullTranscription: 'Eu gostaria de ganhar roupa tamanho 16 e um tênis 39.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '18',
    letterCode: '1770557',
    name: 'Vitória Gabriella Alves',
    age: 13,
    gender: 'F',
    schoolYear: '7º Ano',
    requestSummary: 'Camiseta Keigh e Calça Cargo',
    fullTranscription: 'Eu quero ganhar uma camiseta da Keigh tamanho GG adulto ou uma calça cargo tamanho 42 ou 44.',
    categories: ['Roupa'],
    status: 'available'
  },
  {
    id: '19',
    letterCode: '1859547',
    name: 'Henrique',
    age: 14,
    gender: 'M',
    schoolYear: '8º Ano',
    requestSummary: 'Tênis 42, Pijama, Chuteira 42',
    fullTranscription: 'Tênis nº 42, Pijama, Chuteira nº 42, meias de jogador.',
    categories: ['Calçado', 'Roupa'],
    status: 'available'
  },
  {
    id: '20',
    letterCode: '1859568',
    name: 'Manuelo Ortiz Lopes',
    age: 17,
    gender: 'M',
    schoolYear: '9º Ano',
    requestSummary: 'Tênis 39, Bermuda GG, Sandália',
    fullTranscription: 'Tênis nº 39, Bermuda nº 50 (GG), Camiseta GG, Sandália nº 39.',
    categories: ['Calçado', 'Roupa'],
    status: 'available'
  },
  {
    id: '21',
    letterCode: '1859590',
    name: 'Jandir Vinícius Gonsalves',
    age: 16,
    gender: 'M',
    schoolYear: '7º Ano',
    requestSummary: 'Cuecas, Chinelo 42, Tênis 42',
    fullTranscription: 'Cuecas Box, Chinelo 42, Tênis nº 42, Camiseta M, Bermuda (M), Meias.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '22',
    letterCode: '1859625',
    name: 'Eduardo Fonseca Gonçalves',
    age: 16,
    gender: 'M',
    schoolYear: '7º Ano',
    requestSummary: 'Moletom M, Calça Jeans 38',
    fullTranscription: 'Moletom (M), Calça jeans nº 38, Tênis nº 39, Bermuda, Camiseta (M), boné, meias, cuecas box (P).',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '23',
    letterCode: '1859646',
    name: 'Isabela de Oliveira Soares',
    age: 16,
    gender: 'F',
    schoolYear: '9º Ano',
    requestSummary: 'Tênis 37, Roupas, Calça Jeans 38',
    fullTranscription: 'Tênis e Sandália 37, Calça Jeans nº 38, Calça Legging P, Meias.',
    categories: ['Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '24',
    letterCode: '1859661',
    name: 'Luis Pedro Gonçalves',
    age: 17,
    gender: 'M',
    schoolYear: '-',
    requestSummary: 'Tênis 42, Bermuda, Camiseta G',
    fullTranscription: 'Tênis nº 42, Bermuda e Camiseta tamanho (G).',
    categories: ['Calçado', 'Roupa'],
    status: 'available'
  },
  {
    id: '25',
    letterCode: '1859675',
    name: 'João Vitor Rodrigues',
    age: 16,
    gender: 'M',
    schoolYear: '-',
    requestSummary: 'Tênis 42, Bermuda, Camiseta M',
    fullTranscription: 'Tênis nº 42, Bermuda e Camiseta tamanho (M).',
    categories: ['Calçado', 'Roupa'],
    status: 'available'
  },
  {
    id: '26',
    letterCode: '1859712',
    name: 'Alexandro de Barros',
    age: 16,
    gender: 'M',
    schoolYear: '-',
    requestSummary: 'Tênis 38, Bermuda, Camiseta M',
    fullTranscription: 'Tênis nº 38, Bermuda e Camiseta Tamanho (M).',
    categories: ['Calçado', 'Roupa'],
    status: 'available'
  },
  {
    id: '27',
    letterCode: '1859726',
    name: 'Janderson Xavier',
    age: 17,
    gender: 'M',
    schoolYear: '8º EJA',
    requestSummary: '01 par de tênis nº 41/42',
    fullTranscription: '01 par de tênis nº 41/42.',
    categories: ['Calçado'],
    status: 'available'
  },
  {
    id: '28',
    letterCode: '1771965',
    name: 'Eduardo Angelo',
    age: 14,
    gender: 'M',
    schoolYear: '9º Ano',
    requestSummary: 'Urso Stray Kids, Chapinha',
    fullTranscription: 'Papai Noel, por favor realize meus pedidos. Eu ficaria muito feliz de ganhar. Urso do Stray Kids, Chapinha, Saia de Anime.',
    categories: ['Brinquedo', 'Outros', 'Roupa'],
    status: 'available'
  },
  {
    id: '29',
    letterCode: '1771981',
    name: 'Christian Gabriel',
    age: 14,
    gender: 'M',
    schoolYear: '6º Ano',
    requestSummary: 'Bicicleta, Aparelho de som',
    fullTranscription: 'Bicicleta (pode ser usada), Aparelho de som (pode ser usado). Preciso de uma bike para ir para minha mãe e para dar umas bandas com meu irmão mais novo.',
    categories: ['Brinquedo', 'Outros'],
    status: 'available'
  },
  {
    id: '30',
    letterCode: '1771987',
    name: 'Daniel Alexsandro',
    age: 15,
    gender: 'M',
    schoolYear: 'Escola Especial',
    requestSummary: 'Roupas G, Carrinho controle remoto',
    fullTranscription: 'Roupas Tamanho G; Carrinho controle remoto.',
    categories: ['Roupa', 'Brinquedo'],
    status: 'available'
  },
  {
    id: '31',
    letterCode: '1772026',
    name: 'Enzo Melo',
    age: 13,
    gender: 'M',
    schoolYear: '6º Ano Ed. Especial',
    requestSummary: 'Rádio, Carrinho controle, Bicicleta',
    fullTranscription: 'Rádio, Carrinho controle remoto, Bicicleta, Roupas G.',
    categories: ['Brinquedo', 'Roupa', 'Outros'],
    status: 'available'
  },
  {
    id: '32',
    letterCode: '1772041',
    name: 'Gabriel Gonçalves',
    age: 13,
    gender: 'M',
    schoolYear: '6º Ano Ed. Especial',
    requestSummary: 'Carrinho controle, Bicicleta',
    fullTranscription: 'Carrinho controle remoto, Bicicleta, Roupas tamanho G, rádio.',
    categories: ['Brinquedo', 'Roupa', 'Outros'],
    status: 'available'
  },
  {
    id: '33',
    letterCode: '1772055',
    name: 'Julia Vitória Neto',
    age: 11,
    gender: 'F',
    schoolYear: '4º Ano',
    requestSummary: 'Bicicleta, Roupa Tam 16',
    fullTranscription: 'Bicicleta, roupa tamanho 16, mochila.',
    categories: ['Brinquedo', 'Roupa', 'Material Escolar'],
    status: 'available'
  },
  {
    id: '34',
    letterCode: '1772076',
    name: 'Rafael Marques',
    age: 5,
    gender: 'M',
    schoolYear: 'Creche',
    requestSummary: 'Bicicleta, Carrinho blocos',
    fullTranscription: 'Bicicleta infantil, carrinho blocos encaixe, roupas t. 6, patinete infantil.',
    categories: ['Brinquedo', 'Roupa'],
    status: 'available'
  },
  {
    id: '35',
    letterCode: '1772089',
    name: 'Paulo Renan',
    age: 14,
    gender: 'M',
    schoolYear: '8º Ano',
    requestSummary: 'Bicicleta, Rádio c/ fone, MP3',
    fullTranscription: 'Bicicleta, Rádio c/ fone, Mp3 player.',
    categories: ['Brinquedo', 'Outros'],
    status: 'available'
  },
  {
    id: '36',
    letterCode: '1772105',
    name: 'Artur dos Santos',
    age: 12,
    gender: 'M',
    schoolYear: '3º Ano',
    requestSummary: 'Celular, Carrinho controle remoto',
    fullTranscription: 'Um celular (pode ser usado), carrinho de controle remoto.',
    categories: ['Brinquedo', 'Outros'],
    status: 'available'
  },
  {
    id: '37',
    letterCode: '1772158',
    name: 'Evelyn Kauana',
    age: 16,
    gender: 'F',
    schoolYear: '-',
    requestSummary: 'Roupa 40-42, Maquiagem',
    fullTranscription: 'Roupa (40-42), maquiagem, tênis (37-38).',
    categories: ['Roupa', 'Outros', 'Calçado'],
    status: 'available'
  },
  {
    id: '38',
    letterCode: '1772166',
    name: 'Marcos Piter',
    age: 13,
    gender: 'M',
    schoolYear: '6º Ano',
    requestSummary: 'Bicicleta, Roupas M',
    fullTranscription: 'Bicicleta, Roupas (Tam-M), Tênis (38-39), Boné.',
    categories: ['Brinquedo', 'Roupa', 'Calçado'],
    status: 'available'
  },
  {
    id: '39',
    letterCode: '1772186',
    name: 'Maria Eduarda Peralta',
    age: 14,
    gender: 'F',
    schoolYear: '6º Ano',
    requestSummary: 'Roupas Extra G, Maquiagem',
    fullTranscription: 'Roupas (Extra G), maquiagem, tênis (38-39).',
    categories: ['Roupa', 'Outros', 'Calçado'],
    status: 'available'
  },
  {
    id: '40',
    letterCode: '1772200',
    name: 'Kyara da Silva',
    age: 14,
    gender: 'F',
    schoolYear: '6º Ano',
    requestSummary: 'Maquiagem, Roupas XL, Tênis 38',
    fullTranscription: 'Maquiagem, roupas (TAM-XL), tênis (38), material escolar, mochila.',
    categories: ['Outros', 'Roupa', 'Calçado', 'Material Escolar'],
    status: 'available'
  },
  {
    id: '41',
    letterCode: '1772209',
    name: 'Louiza Vitória',
    age: 13,
    gender: 'F',
    schoolYear: '7º Ano',
    requestSummary: 'Roupas (M), Maquiagem, Tênis',
    fullTranscription: 'Roupas (M), maquiagem, tênis (38-39).',
    categories: ['Roupa', 'Calçado', 'Outros'],
    status: 'available'
  },
  {
    id: '42',
    letterCode: '1772224',
    name: 'Felipe Melo',
    age: 15,
    gender: 'M',
    schoolYear: '7º Ano',
    requestSummary: 'Bicicleta, Tênis Mizuno 38-39',
    fullTranscription: 'Bicicleta, Tênis Mizuno (38-39), Roupas (Tam-M-42), Boné.',
    categories: ['Brinquedo', 'Calçado', 'Roupa'],
    status: 'available'
  },
  {
    id: '43',
    letterCode: '1772241',
    name: 'Benício de Souza Felippe',
    age: 9,
    gender: 'M',
    schoolYear: '3º Ano',
    requestSummary: 'Bicicleta',
    fullTranscription: 'Olá Papai Noel, sou o Benício... Adoro brincar no pátio com meus amiguinhos, já tenho uma motoquinha mas fico muito feliz quando vejo uma bicicleta, já quero subir.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '44',
    letterCode: '1772249',
    name: 'Bruna Natali',
    age: 7,
    gender: 'F',
    schoolYear: '2º Ano',
    requestSummary: 'Patins com equipamento de segurança',
    fullTranscription: 'Gostaria de ganhar um patins calço numero 32, mas acredito que tenha que ser maior. Já, também os equipamentos de proteção para poder brincar com segurança.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '45',
    letterCode: '1772253',
    name: 'Brayan Manoel',
    age: 15,
    gender: 'M',
    schoolYear: '-',
    requestSummary: 'Conjunto do Internacional',
    fullTranscription: 'Sou torcedor do internacional de porto alegre e gostaria de ganhar o conjunto oficial (camisa preta).',
    categories: ['Roupa'],
    status: 'available'
  },
  {
    id: '46',
    letterCode: '1772264',
    name: 'Giovana Antonela',
    age: 1,
    gender: 'F',
    schoolYear: '-',
    requestSummary: 'Triciclo de empurrar',
    fullTranscription: 'Tenho 1 ano e 4 meses... Gostaria de ganhar um triciclo para que minha mamãe possa passear comigo, já que ainda faço fisioterapia para poder caminhar.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '47',
    letterCode: '1772282',
    name: 'Paulo Alexandre',
    age: 4,
    gender: 'M',
    schoolYear: '-',
    requestSummary: 'Fantasia Homem Aranha',
    fullTranscription: 'Moro no abrigo... adoro brincar e vestir fantasias. Papai Noel gostaria de uma fantasia completa do homem aranha com máscara.',
    categories: ['Roupa', 'Brinquedo'],
    status: 'available'
  },
  {
    id: '48',
    letterCode: '1772296',
    name: 'Mikaelly Rosa',
    age: 5,
    gender: 'F',
    schoolYear: 'Jardim B',
    requestSummary: 'Bicicleta',
    fullTranscription: 'Moro no abrigo... gosto de brincar de boneca e andar no pátio. Gostaria de uma bicicleta para poder pedalar e aproveitar os dias de verão.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '49',
    letterCode: '1772304',
    name: 'Aurora Rosa',
    age: 1,
    gender: 'F',
    schoolYear: '-',
    requestSummary: 'Triciclo de empurrar',
    fullTranscription: 'Tenho 1 e 9 meses... gosto de brincar com meus brinquedos. Gostaria de ganhar um triciclo para que possa passear com as tias do abrigo.',
    categories: ['Brinquedo'],
    status: 'available'
  },
  {
    id: '50',
    letterCode: '1776617',
    name: 'Alexandro Seuis',
    age: 13,
    gender: 'M',
    schoolYear: '-',
    requestSummary: 'Roupas, Tênis, Bicicleta',
    fullTranscription: 'Roupas (Tam-M), Tênis (38-39), Bicicleta, Mochila, Material Escolar.',
    categories: ['Roupa', 'Calçado', 'Brinquedo', 'Material Escolar'],
    status: 'available'
  }
];